version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
  redis-cache:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/rediscache
      - ./.ivy2:/root/.ivy2
      - ./.sbt:/root/.sbt
    links:
      - redis
    depends_on:
      - redis
    environment:
      - PORT=8080
      - HOST=redis-cache
      - REDISHOST=redis
  e2e:
    build:
      context: .
      dockerfile: Dockerfile.test
    links:
      - redis
      - redis-cache
    depends_on:
      - redis
      - redis-cache
    environment:
      - PORT=8081
      - HOST=redis-cache
      - REDISHOST=redis
    command: "sbt test cucumber"
volumes:
  redis-data:

