version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
  redis-cache:
    image: erinkav/redis-cache
    ports:
      - "8080:8080"
    depends_on:
      - redis
    command: sbt run


