version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
  redis-cache:
    image: erinkav/redis-cache
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/exampleapp
      - ./.ivy2:/root/.ivy2
      - ./.sbt:/root/.sbt
    links:
      - redis
    depends_on:
      - redis
    entrypoint: sbt run
    environment:
      - REDISHOST=redis
      - HOST=0.0.0.0

volumes:
  redis-data:

